### PR TITLE
Add received pdf endpint

### PR DESCRIPTION
**Pull request by ankitdimania-eligible**

### CODE REVIEW

**Comment by ankit819** [comment]
Looks good.
Please fix https://codeclimate.com/github/eligible/eligible-ruby/compare/ankitd/received_pdf before merging.

**Comment by ankitdimania-eligible** [comment]
@ankit819 done. Please check this change also https://github.com/eligible/eligible-ruby/pull/23/files#diff-cb34ab2845146e508f6d0b96f980dd0eR135

**Comment by ankit819** [comment]
Looks good. :+1:

**Comment by ankitdimania-eligible** [comment]
ankit [8:20 PM] 
okk, good to go

**Pull request merged**
